### PR TITLE
Fix broken link "How to make mistakes in Python"

### PR DESCRIPTION
**Pull request by Glyphack**

### CODE REVIEW

**Comment by charlax** [comment]
Thanks! Would you mind rewriting the history so that it's only one commit on top of `master`? Thanks!

**Comment by Glyphack** [comment]
Oops, I tried to use Github online code spaces looks like its default strategy is merge 😄. Done.

**Comment by charlax** [comment]
Awesome thanks!

**Comment by iOSMaL** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Pull request merged**
