### PR TITLE
Update to include the book "x86-64 Assembly Language Programming with Ubuntu" by Ed Jorgensen

### PR DESCRIPTION
**Pull request by tathyagarg**
# Why this book should be added
The book "x86-64 Assembly Language Programming with Ubuntu" covers all the information you need to get started with writing assembly code. Starting with an introduction discussing the benefits of assembly, and an extensive description of the architecture covering every prerequisite. 
It includes a section on debugging your programs using DDD, so you can inspect and watch the variables in your code update in real time. With an introduction discussing basic computer architecture, and a conclusion talking about system interrupts and parallel computing, it truly arms readers with all they need to write efficient assembly code.

### CODE REVIEW

**Comment by Sudouble** [comment]
来件已收到，我会尽快处理！

**Comment by iOSMaL** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Review by sanbei011 — APPROVED** [review]
that's good

**Comment by charlax** [comment]
Yes, that's a good resource, thanks!

**Pull request merged**
