### PR TITLE
Added one useful resource

### PR DESCRIPTION
**Pull request by Paras-96**
Added the What is a Software Developer? Definition, Skills, and Career URL to the section - Must-read articles provide useful insights to aspiring software development engineers.

Please let me know if further changes are required.

Thank you

### CODE REVIEW

**Comment by Sudouble** [comment]
来件已收到，我会尽快处理！

**Comment by iOSMaL** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Review by roschart — APPROVED** [review]

**Review by Linder5865 — APPROVED** [review]

**Review by ayazjam — APPROVED** [review]

**Comment by charlax** [comment]
Hey - thanks for your contribution. This resource is not adding enough value to the list.

**Comment by iOSMaL** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by Sudouble** [comment]
来件已收到，我会尽快处理！

**Pull request closed without merging**
